### ISSUE TITLE
What's needed to make 5.12+ compatible?

### ISSUE THREAD

**Issue by danaskallman** [CiviCooP/org.civicoop.caselink#2]
Looking into this extension and the compatibility state 4.6. What's needed to make compatible with current CiviCRM release (5.12)?

**Comment by jaapjansma** [comment]
Did you try to install this extension in 5.12 and did it work? Or what did not work?

**Comment by danaskallman** [comment]
It seems to be working with what I am able to see it does. If there are now issues, shall the version compatible be updated?

**Comment by jaapjansma** [comment]
Yes the version compatibility should be updated and you can do that.

**Comment by danaskallman** [comment]
It seemed to work from my few tests exploring the extension. Will close this and can be re-opened if needed.
