### ISSUE TITLE
Ability to associate the same event to multiple cases

### ISSUE THREAD

**Issue by danaskallman** [CiviCooP/org.civicoop.caselink#3]
Is it possible to have one event that is associated with multiple cases? If not, is this a useful addition to explore?

**Comment by jaapjansma** [comment]
At the moment that is not possible. But it is a useful addition. What is the use case behind it?

**Comment by danaskallman** [comment]
The use case is an application process for a two-week training program, that  20 people can attend if accepted. The training runs throughout the year and each applicant/case selects their preferred training date. So in this specific case 20 cases would be connected to one event or training. Does that make sense?

**Comment by jaapjansma** [comment]
It doesnt make sense. But would it not be better to record the event_id on the case instead? Or record the case_id on the participant record.

**Comment by jaapjansma** [comment]
The original use case for linking a case to an event was with an organisation which provides training for business. The case in civicrm holds all the arrangement with the business. E.g. how many trainings are given, how many people, for how much money etc... The case is the contract, the event is an execution of the contract. This way an event could be traced back to a contract.

**Comment by danaskallman** [comment]
It's around 26 trainings a year per program and there are 4 programs. Each training holds 20 people and there is just a small application fee of $25. Is that what you mean? 

Would it be something that can be added or it's own extension?

**Comment by jaapjansma** [comment]
What I mean, is that it would be better to store a reference to the partcipant record on the case rather than to the event. I do think that is doable in your own extension.

**Comment by danaskallman** [comment]
Ah, I see. Yes, store and display in the case to show what training was attended for the application. Events would be created for the year and then applied to the case throughout the year.

**Comment by danaskallman** [comment]
@mecachisenros thoughts?

**Comment by danaskallman** [comment]
Closing since what I was looking for was connected to participants and case, not one event one case. Thanks!
